function [ m ] = hu_moments( img )
% This function calculate Hu moments of an input image.

m1 = normalized_central_moment(img,2,0) + ...
    normalized_central_moment(img,0,2);

m2 = m1^2 + 4 * normalized_central_moment(img,1,1)^2;

m3 = (normalized_central_moment(img,3,0) - ...
    3*normalized_central_moment(img,1,2))^2 + ...
    (normalized_central_moment(img,0,3) - ...
    3*normalized_central_moment(img,2,1))^2;

m4 = (normalized_central_moment(img,3,0) - ...
    normalized_central_moment(img,1,2))^2 + ...
    (normalized_central_moment(img,0,3) - ...
    normalized_central_moment(img,2,1))^2;

m = [m1, m2, m3, m4];
end

